version: '3.4'

services:
  memorizewords:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 8000:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - memorizewords-db
      
  memorizewords-db:
     container_name: memorizewords-db
     image: "mcr.microsoft.com/mssql/server:2022-latest"
     ports:
       - "1433:1433"
     environment:
       SA_PASSWORD: "12345678A@"
       ACCEPT_EULA: "Y"
     volumes:
       - ./volume/mssql/data:/var/opt/mssql/data

#saa;#O0je~dyx9cNpZ40me

#  sonarqube:
#    image: sonarqube
#    expose:
#      - 9000
#    ports:
#      - "127.0.0.1:9000:9000"
#    networks:
#      - sonarnet
#    environment:
#      - sonar.jdbc.username=sonar
#      - sonar.jdbc.password=sonar
#      - sonar.jdbc.url=jdbc:postgresql://db/sonar
#    volumes:
#      - sonarqube_conf:/opt/sonarqube/conf
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

#  db:
#    image: postgres:12
#    networks:
#      - sonarnet
#    environment:
#      - POSTGRES_USER=sonar
#      - POSTGRES_PASSWORD=sonar
#    volumes:
#      - postgresql:/var/lib/postgresql
#      - postgresql_data:/var/lib/postgresql/data

#networks:
#  sonarnet:

#volumes:
#  sonarqube_conf:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_bundled-plugins:
#  postgresql:
#  postgresql_data: